# Generated by Django 6.0.1 on 2026-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('productCode', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.TextField(blank=True, null=True)),
                ('screen_resolution', models.TextField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
