# Generated by Django 5.2.6 on 2026-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='redPrice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
